### ISSUE TITLE
window too large on lower resolutions

### ISSUE THREAD

**Issue by Griiimon** [NiclasEriksen/leif-simulator#2]
On a notebook with lower resolution the window is too large to see the menu bar on the left hand side. 

Possible solution: Call OS.set_window_maximized(true) on startup

**Comment by NiclasEriksen** [comment]
[bab2832](https://github.com/NiclasEriksen/game-of-leif/commit/bab2832aba7c55212027675bc9e6d081800497b7)

[Release](https://github.com/NiclasEriksen/game-of-leif/releases/tag/v0.2.2-alpha)

Thank you for that note, the temporary solution has been added. I'm in the process of reworking the UI completely and will move the rendering of the world to it's own viewport of a fixed (configurable) size, and have the UI scale properly to screen resolutions. Using the current viewport scaling was a quick and lazy approach anyway.
